# Mesoscale Microstructure Simulation Project
# Travis Continuous Integration build script
# for Spinodal Decomposition benchmark problems
# Questions/comments to trevor.keller@gmail.com (Trevor Keller)

language: cpp
os: linux
dist: trusty
sudo: required

compiler:
    - gcc

env:
    - MPI=openmpi

notifications:
    email: false

install:
    - sudo apt-get update -qq -y
    - sudo apt-get -y install -qq openmpi-bin libopenmpi-dev

script:
    - bash run_benchmarks.sh --np 2 --noviz

after_script:
    - cat results.yml

